# Copyright 2020 Kaloian Manassiev
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
# associated documentation files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute,
# sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
# NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Import('env')

common = env.Library(
    target='common',
    source=[
        'base.cpp',
        'commands_server.cpp',
        'compressing_tunnel_frame_pipe.cpp',
        'connection.cpp',
        'context_base.cpp',
        'exception.cpp',
        'file_descriptor.cpp',
        'ip_parsers.cpp',
        'signing_tunnel_frame_pipe.cpp',
        'socket_producer_consumer.cpp',
        'tun_ctl.cpp',
        'tunnel_frame.cpp',
        'tunnel_producer_consumer.cpp',
    ],
)

Return('common')
