# Copyright 2021 Kaloian Manassiev
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
# associated documentation files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute,
# sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
# NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

import os

Import('env')

drivers_env = env.Clone()
drivers_env.Append(CPPPATH=[
    drivers_env.Dir('.').srcnode(),
    drivers_env.Dir('bcm2835/include').srcnode(),
])
drivers_env.Append(LIBPATH=[
    drivers_env.Dir('bcm2835/lib').srcnode(),
])

architectures = drivers_env['ARCHITECTURES']
drivers_architecture = 'pi'
arch = architectures[drivers_architecture]

env = drivers_env
SConscript('SIM7600X-4G-HAT/SConscript', exports='env', duplicate=0)
